@startuml
title Diagramme de classes - Foodtruck

class Pizza {
    - id : int
    - name : string
    - ingredients : string
    - imageUrl : string
    - price : float
    - created_at : datetime
    - updated_at : datetime

    + create() : Pizza
    + findAll() : Pizza[]
    + findById(id : int) : Pizza
    + update(id : int) : Pizza
    + delete(id : int) : void
}

class Ingredient {
    - id : int
    - name : string
    - price : float
    - created_at : datetime
    - updated_at : datetime

    + create() : Ingredient
    + findAll() : Ingredient[]
    + findById(id : int) : Ingredient
    + update(id : int) : Ingredient
    + delete(id : int) : void
}

Pizza "1..*" -- "1..*" Ingredient : contient

@enduml